### ISSUE TITLE
issue with shows argumant

### ISSUE THREAD

**Issue by declan727** [cockroach/episoder#2]
while trying to run "episodes shows" I am receiving

[   1] 295647
       %s, %s, %s
Traceback (most recent call last):
  File "/usr/local/bin/episoder", line 375, in <module>
    main()
  File "/usr/local/bin/episoder", line 371, in main
    args.func(args)
  File "/usr/local/bin/episoder", line 144, in shows
    statusStrings[status], enabledStrings[show.enabled])
TypeError: unsupported operand type(s) for %: 'NoneType' and 'tuple'

it appears to be with the Blindspot tv show however if I start a new database I can reproduce with any show even if there is only one show in the database.

**Comment by cockroach** [comment]
Thanks for the report. This should now be fixed.
